#docker-compose.yml

version: "3.8"
services:
  app:
    build: .
    ports:
      - "9870:9870"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=file:./dev.db
